{
 "title": "FiveM",
 "description": "FiveM Dashboard to monitoring some features on FiveM. (Your target on Prometheus must be named as \"fxserver\")",
 "tags": [ "FiveM" ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "Datasource", "label": "Prometheus", "query": "prometheus" },
   { "name": "job", "query": { "query": "metrics(^fxs_.*)" } }
  ]
 },
 "panels": [
  {
   "title": "Connected players",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "fxs_player_count{job=\"fxserver\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Player count",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 10, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "fxs_player_count{job=\"fxserver\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Connections / disconnections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 14, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "fxs_player_connections{job=\"fxserver\"}",
     "legendFormat": "Connections"
    },
    {
     "expr": "fxs_player_disconnections{job=\"fxserver\"}",
     "legendFormat": "Disconnections"
    }
   ]
  },
  {
   "title": "Average latency (ms)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 14, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "fxs_average_player_latency{job=\"fxserver\"}",
     "legendFormat": "Average latency"
    }
   ]
  },
  {
   "title": "Latency (min/max) (ms)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 14, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "fxs_max_player_ping{job=\"fxserver\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "fxs_min_player_ping{job=\"fxserver\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Server events",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "fxs_events_server{job=\"fxserver\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "fxs_events_client{job=\"fxserver\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latency - Heatmap",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "fxs_players_latency_bucket{job=\"fxserver\"}",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Object count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "fxs_object_count{job=\"fxserver\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Vehicle Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 6, "y": 32 },
   "targets": [
    {
     "expr": "fxs_vehicle_count{job=\"fxserver\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Ped count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 32 },
   "targets": [
    {
     "expr": "fxs_ped_count{job=\"fxserver\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Object count",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 40 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "fxs_object_count{job=\"fxserver\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Vehicle count",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 40 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "fxs_vehicle_count", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Ped count",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 40 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "fxs_ped_count{job=\"fxserver\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}